populationgenomics/cpg-infrastructure

tokens/main.py
tokens/repository-map.json

- Move Production-pipelines to an 'always allowed' repo (linked to https://github.com/populationgenomics/production-pipelines/issues/153)
- Remove rare-disease from most repositories (The RD [data_transfer](https://github.com/populationgenomics/rare-disease/tree/main/data_transfer) scripts have already been migrated to an always-run repo [analysis-runner](https://github.com/populationgenomics/analysis-runner/tree/main/scripts), and should be removed from rare-disease)
Possible extra?
- move AIP to an always-run repo
- currently allowed on 19/39 datasets, and likely to be applied to analysis cohorts as they are added
- Could be useful to add to the blanket approval list and save a few PRs later

move production-pipelines to always allowed

---

tokens/main.py

Noop change, just useful when I wanted to run `python tokens/main.py`

Make generating tokens path-agnostic

---

cpg_infra/abstraction/base.py
cpg_infra/abstraction/gcp.py

Context: https://centrepopgen.slack.com/archives/C03FZL2EF24/p1666607536387039

Add lifecycle rule to GCP buckets to delete incomplete multipart uploads

---

cpg_infra/abstraction/base.py
cpg_infra/abstraction/gcp.py
cpg_infra/config.py
cpg_infra/driver.py
stack/Pulumi.fewgenomes.yaml

Will be useful for a universially dependent `cpg-common` dataset with an artifact registry, eventually removing the support for specifying cpg-common manually.
\+ Import the pre-existing fewgenomes repository.

Implement container registry for a dataset

---

cpg_infra/driver.py

- Should indirectly solve notebooks access to cpg-common images.

Add access group to artifact registry reader

---

stack/production.yaml

bump budget to accomodate for ~25TB of CRAMs
(At 0.30 per GB + ~10%)

Bump Prophecy Budget

---

cpg_infra/driver.py

- readonly_depends doesn't work because they're not included in analysis-group.

Adjust project bucket lister permissions

---

cpg_infra/driver.py

Context: https://centrepopgen.slack.com/archives/C03FZL2EF24/p1675647031435499?thread_ts=1675646555.315329&cid=C03FZL2EF24
Looks like Pulumi doesn't like to create empty blobs for empty groups, so we add a newline in the end.
This is handled fine when reading: https://cs.github.com/populationgenomics/cpg-utils/blob/f9f63b64fc0b79ffb62291ff478f5b5b2933ddfa/cpg_utils/cloud.py?q=is_member_in_cached_group#L307

Gracefully handle groups without members for cache blobs

---

cpg_infra/driver.py

This reverts commit 19716733a0b67f9b3f28faa12028f47dcbf43dec.
Context: https://centrepopgen.slack.com/archives/C03FZL2EF24/p1675662078878649?thread_ts=1675659698.052339&cid=C03FZL2EF24

Revert "Gracefully handle groups without members for cache blobs (#46)"

---

requirements.txt
stack/requirements.txt

This will be useful to clean up the state after migrating to Autoclass buckets, but I'd like to apply any unrelated changes independently, to avoid confusion.

Update pulumi-gcp to get BucketAutoclassArgs support

---

cpg_infra/billing_aggregator/aggregate/utils.py

With interval less than the AEDT offset, this is missing all GCP billing data.

Move default to UTC time

---

.pylintrc
cpg_infra/billing_aggregator/driver.py

Initial deploy failed as the increase of memory needs to align with an increase in CPU by this table: https://cloud.google.com/functions/docs/configuring/memory

Increase CPU to redeploy billing_aggregator

---

cpg_infra/abstraction/gcp.py
cpg_infra/config.py
cpg_infra/driver.py

- Support checking our private repositories from hail
- Add token in infrastructure config for use by analysis-runner

Add hail accounts secret_accessor to hail-git-token

---

cpg_infra/abstraction/hailbatch.py
cpg_infra/config.py
cpg_infra/driver.py

- Only check membership map for external users (broke non-external users on Azure, like hail batch accounts in groups)
- Small fix for creating hail batch billing projects
- Sort hail batch members to reduce fluctuation for same username members (but different emails)
- Already deployed

Group membership fixes

---

cpg_infra/abstraction/hailbatch.py

I think mypy would've caught this, so I'll look at adding it into this repo

Fix non-callable resp.text call for hailbatch

---

cpg_infra/abstraction/azure.py
cpg_infra/abstraction/gcp.py
cpg_infra/billing_aggregator/driver.py
cpg_infra/config.py
cpg_infra/driver.py

When I tore down our infrastructure, it didn't delete the accounts properly, so now `cpgcommon` is permanently unavailable, and only allowed `[a-z][a-z0-9]{3,24}` so we're quite stuck except to append number or pick a new prefix

Split dataset storage prefix by cloud

---

cpg_infra/abstraction/metamist.py
cpg_infra/config/config.py
cpg_infra/driver.py
requirements.txt

Create the metamist project through Pulumi through another dynamic resource provider.
We only want to create _one_ per dataset, so now is a natural point to make the model support this.
Now, insert a new CPGDatasetInfrastructure in between CPGInfrastructure and CPGDatasetCloudInfrastructure. And make the generic Dataset one do the instantiation of the clouds. Simplified some logic at the top level, allows for single dataset infrastructure in one of the specific cloud providers (or cloud agnostic).
Introduces some simplifications, like accessing the "common" dataset to create infrastructure in, at the top level.
Adds `metamist` as a dependency (the new pypi version, even though it's not technically current, the method names for project won't change).

Metamist project creation + small dataset manager refactor

---

cpg_infra/abstraction/metamist.py

Invalid return value, returns an int, not a project dictionary.

FIX Bad metamist project creation

---

.github/workflows/lint.yaml
.github/workflows/preview.yaml

Akin to populationgenomics/cpg-infrastructure-private#182, this sets up `git+https://` authentication credentials via a credential helper in each of the workflows that needs to pip install metamist-infrastructure, which is done by checking out the relevant code from the sample-metadata repository — which is currently private so accessing it requires credentials.
See the cpg-infrastructure-private PR for further details of the technique used.

Authenticate GitHub access in actions workflows

---

cpg_infra/driver.py
pyproject.toml
requirements.txt

Use project_id, not the project directly to avoid the `projects/` prefix
+ resort imports

Artifact registry v2 (+ req bump)

---

cpg_infra/config/config.py

Before we can deploy the latest Metamist ETL, we would need to add extra config to SampleMetadata class, here are my suggestions.
All are prefixed as ETL_

Changes to SampleMetadata config class.

---

cpg_infra/abstraction/base.py

This had been left as copy/pasted from the adjacent function definition.
This is indeed _n_ days after creation (one might guess it could instead be _n_ days after the last access):
* The _azure.py_ implementation uses `days_after_modification_greater_than`, which is unambiguous;
* The _gcp.py_ implementation sets `gcp.storage.BucketLifecycleRuleConditionArgs(age=days)`, and `age` is described as being “[measured from the resource's creation time](https://cloud.google.com/storage/docs/lifecycle#age)”.

Fix bucket_rule_temporary() docstring

---

.github/workflows/storage_visualization.yaml

Running out of disk space during this step, and I have noticed larger pip caches

Disable storage vis submit pip cache

---

.github/workflows/lint.yaml

A later step uses `steps.runtests.outputs.rc` but somewhere along the line that `runtests` id was accidentally removed — or perhaps it was never added. Presumably checking `steps.runtests.outputs.rc` defaults to 0…
(Minor issue found via [actionlint](https://github.com/rhysd/actionlint).)

Fix lint action error checking

---

cpg_infra/billing_aggregator/aggregate/gcp.py
cpg_infra/billing_aggregator/aggregate/seqr.py
cpg_infra/billing_aggregator/aggregate/utils.py
cpg_infra/billing_aggregator/monthly_aggregate/main.py

Using the property _PARTITIONDATE to query our billing tables to increase efficiency.
NOTE: This WILL NOT WORK AS INTENDED until the table is partitioned. This will be imminent.
It's also worth noting that the bigquery keyword BETWEEN is date inclusive of the start and end.

Add partition logic to agg

---

cpg_infra/billing_aggregator/aggregate/seqr.py
cpg_infra/billing_aggregator/aggregate/utils.py
cpg_infra/driver.py

This is a reasonably appropriate fix for the problem, it's a max 24 hour difference, and our timing for updating analysis is basically within that tolerance.

Seqr BQ billing data should use prop map by usage_end_time

---

cpg_infra/abstraction/gcp.py
cpg_infra/billing_aggregator/driver.py

Give billing.coordinator_machine_account billing.viewer role to be able to interrogate projects' budget and update the BQ table.

Give billing.coordinator_machine_account billing.viewer role

---

cpg_infra/abstraction/gcp.py

#148 
previously a `BucketMembership.MUTATE` bucket membership would assign the storage.admin role which has elevated privileges including allowing deletion of the bucket. Changing to `storage.objectAdmin` reduces these privileges to only allow manipulation of the bucket contents but not the bucket itself.
The roles differ by `storage.admin` having the following wildcard entries:
```
storage.buckets.*
storage.managedFolders.*
```
whereas `storage.objectAdmin` has:
```
storage.managedFolders.create
storage.managedFolders.delete
storage.managedFolders.get
storage.managedFolders.list
```
and no `storage.buckets` permissions. All other permissions are the same between the roles.
So in effect this change removes the following permissions from the bucket mutate membership:
``` …
```

Disallow deletion of GCP buckets for MUTATE bucket membership type (part 1)

---

cpg_infra/abstraction/gcp.py

Second part to #194 
Closes #148

Disallow deletion of GCP buckets for MUTATE bucket membership type (part 2)

---

storage_visualization/main.py

Because it's failing the weekly storage_visualisation: https://batch.hail.populationgenomics.org.au/batches/433053/jobs/1

Fix typing for hail batch

---

storage_visualization/disk_usage.py
storage_visualization/treemap.py

The storage visualisation bot is failing because we don't require all buckets with the prefix to exist. A potentially more clean approach would be to look at the storage section in the config, and iterate through the listed buckets, rather than look at the prefix - but that's for another time.
Failing job: https://batch.hail.populationgenomics.org.au/batches/433223/jobs/57
```
Traceback (most recent call last):
File "/cpg-infrastructure/storage_visualization/disk_usage.py", line 110, in <module>
main()
File "/cpg-infrastructure/storage_visualization/disk_usage.py", line 82, in main
for blob in blobs:
File "/usr/local/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 208, in _items_iter
for page in self._page_iter(increment=False):
File …
```

Support missing buckets in storage_visualisation bot

---

cpg_infra/billing_aggregator/aggregate/hail.py
cpg_infra/billing_aggregator/aggregate/seqr.py
cpg_infra/billing_aggregator/aggregate/utils.py

Rather than:
1. getting all batches, then
2. getting all jobs for chunks of batches, then
3. process the entries, inserting early when size of entries is high
Let's change some of this to yield entries back, and process on the fly:
1. Get all batches, then
2. For chunks of batches, trigger off the get_jobs call
3. Grab each job as it's loaded and add to a queue,
4. Process jobs as we get them, from any batch, at any time
5. Insert them all at once, or whenever we reach 10MB (but this is configurable)

Improve memory efficiency of billing aggregators

---

.github/workflows/lint.yaml
.pre-commit-config.yaml
cpg_infra/billing_aggregator/aggregate/utils.py
cpg_infra/driver.py
pyproject.toml
reorder_state_file.py
storage_visualization/main.py

There's some ambiguity with graphlib, as it moved from external to internal in 3.11, but Ruff doesn't support the isort py_version argument. Broadly I think this is actually okay, I'm not fussed with it's placement, as long as it's not inconsistently moved.

Remove isort + fix pyproject to sort

---

cpg_infra/abstraction/azure.py
cpg_infra/abstraction/base.py
cpg_infra/abstraction/gcp.py
cpg_infra/driver.py

The name of a secret and pulumi key (the unique key that identifies the secret) are explicitly linked, but I want to create two secrets with specific names within the same dataset scope.
So allow the driver to override the pulumi key, and then use this for the cromwell key that I want two of (temporarily).

Override resource key on secret creation

---

README.md
cpg_infra/config/config.py
cpg_infra/driver.py

- Allow users marked as `can_access_internal_dataset_logs` to access both hail batch accounts + dataproc logs.
- Remove project from a newly added SecretIamMember call as it's not used (but would cause a replace) [I don't know why you can even specify a project there + it was specified incorrectly anyway]
Context: https://centrepopgen.slack.com/archives/C030X7WGFCL/p1713240109483689?thread_ts=1712720352.383989&cid=C030X7WGFCL

Allow internal users to access dataproc logs

---

cpg_infra/billing_aggregator/aggregate/utils.py
cpg_infra/billing_aggregator/driver.py

This PR is fixing 2 issues:
1. When scheduler publishes message to Topic, it is not valid json record. Function get_batch_ids_from_request was an inspired by get_start_and_end_from_request and that re-throws Exception, which is caught one level up.
Function get_batch_ids_from_request is simpler, if not valid json object present then batch_ids is not present, simply return None.
2. Updating BQ materialised views via Pulumi is a bit catch 22, it seems the only possible solution is to remove the view and then created back. This PR is removing the view first.
There will be following PR which add it back in.

Fix billing aggregate issues

---

cpg_infra/billing_aggregator/aggregate/utils.py

When very large batches are being loaded (e.g. https://batch.hail.populationgenomics.org.au/batches/444166), cloud function was running out of memory. This particular batch had over 370K jobs, which generated over 4 million records for the billing BQ table.
We had decided to aggregate hail batches if they reach 50K jobs.

Limit hail batches to max 50K jobs, aggregate any larger ones.

---

cpg_infra/billing_aggregator/aggregate/seqr.py

Background, when trying to process batch https://batch.hail.populationgenomics.org.au/batches/430882
, which took over a week to process, the function runs out of memory because it is trying to prepare the list of all gcp records for that time. Even most of them would be already upserted as seqr scheduled aggregation runs every 4 hours.
This PR checks if records exist and only add it to a list if not present.
This should minimise the list passed around and therefore minimising function RAM requirements.

Seqr - memory optimisation - only add missing records to the list of entries to be updated.

---

storage_visualization/disk_usage.py
storage_visualization/main.py

`prepare_git_job` was moved without a deprecated stub, so fix that and other imports in this repo.

Use update cpg-utils path-names

---

storage_visualization/disk_usage.py
storage_visualization/main.py
storage_visualization/treemap.py

An intermediate storage viz (https://batch.hail.populationgenomics.org.au/batches/445677) failed for an [out-of-memory issues](https://batch.hail.populationgenomics.org.au/batches/445677/jobs/5).
There are two options, but the easiest is to bump the memory, and fail the dataset. Some later options is partition by bucket instead of dataset, but let's do it later if we need.
Also make the last aggregate bash always run, and just post an error if datasets are missing.
Also, noting the actual path construction was pretty disconnected, an output_prefix was supplied, but then the output_path function was used later to construct the web URL prefix. I tested the aggregation works locally.

Make storage-viz more durable

---

cpg_infra/billing_aggregator/aggregate/requirements.txt
cpg_infra/billing_aggregator/driver.py
cpg_infra/config/config.py

This PR includes:
- replace Pub/Sub approach for loading billing data with Cloud Scheduler, which allows to run for up to 1 hours (Pub/Sub has 9 mins limit)
- remove the update billing budget function as this is not used and will be implemented as part of cpg-infra-private GitHub action.

Replacing Billing Aggregate Pub/Sub with Cloud Scheduler

---

cpg_infra/abstraction/metamist.py
cpg_infra/driver.py

Relates to populationgenomics/metamist#829
- Update custom metamist project member provider to send through a list of members and roles for a project, rather than adding members to specific groups.
- Add contributor role for anyone tagged as an analysis member

Update metamist project member provider to handle new permissions structure

---

cpg_infra/driver.py

Adds wheel bucket read members to group to avoid bucket member limit.
Storage buckets have a limit of 250 members, which we are going over after the addition of a new dataset. This change adds those members to a group before adding the group to the bucket to work around the limit

Hail wheel bucket member limit fix (part 1)

---

cpg_infra/billing_aggregator/aggregate/gcp.py
cpg_infra/billing_aggregator/aggregate/requirements.txt
cpg_infra/billing_aggregator/aggregate/seqr.py
cpg_infra/billing_aggregator/aggregate/utils.py

This change:
1. Optimise BQ queries, which did not use the benefit of partitions. Would lower the cost of running the queries.
2. Some of the filters were too restrict, esp. when checking existing ids by usage_end_time, this is fixing bug with some random duplicated records.
3. pin numpy to <2, as some versions of python have issue with version 2.0 as mentioned here: https://github.com/numpy/numpy/issues/26710

Adjust Billing BQ filters to use partitions

---

cpg_infra/billing_aggregator/driver.py

Recent runs did reach up to 2.7GB of ram, increase the RAM for seqr billing to 3GB.

Increase RAM for Seqr aggreg billing job.

---

cpg_infra/billing_aggregator/driver.py

Following the other pattern, I think it's supposed to use the `.name.`
Testing this locally, it looks like it should be fine

[gcp-cost-control] Fix: Use the archive object name

---

cpg_infra/billing_aggregator/aggregate/utils.py

Recent runs of seqr and hail were timing out on hail api. It took close to 60 seconds, had increased timeout to 90 seconds, which should sort out those errors.
As well limit the += to only 5 days, that 10 days seems to get too many ids, 3-5 days should be enough to check against data already in the table.

Billing timeout and filter constant changes.

---

cpg_infra/billing_aggregator/gcp_cost_report_slack_bot/requirements.txt

https://centrepopgen.slack.com/archives/C0236RXT54J/p1723412715236259?thread_ts=1723330810.902589&cid=C0236RXT54J
I can't replicate locally, but it might be due to a change to grpcio: 
- https://github.com/grpc/grpc/issues/37178#issuecomment-2227719358
- https://github.com/grpc/grpc/issues/37222
I cannot for the life of me work out how to find the version of grpcio in the cloud functions container - I've tried looking up the build logs, running the container but doesn't seem to get me anywhere.

Pin grpcio to reduce logging

---

cpg_infra/driver.py

This new group is attached to cpg-config bucket.
All the analysis groups will be added as members, instead of directly attached to cpg-config bucket.
This will prevents 250 hard GCP limit on attached groups per resource we are currently experiencing.
Deployment will be done in steps.
1. Creating new group and attach all the existing analysis groups to it. (this PR)
2. Test, manually remove fewgenoms ar-groups from the cpg-config bucket and and submit a batch via AR, check for any permissions issues
3. If test is successful, then remove code on line 2603 as per [TODO comment](https://github.com/populationgenomics/cpg-infrastructure/blob/7985ece94fca4c63e2b2306c8aaee7e68e1f4ce1/cpg_infra/driver.py#L2603)

New AR-config-viewer group

---

cpg_infra/billing_aggregator/aggregate/requirements.txt
cpg_infra/billing_aggregator/driver.py

Hail aggregate function needs more than 3GB for processing, older pandas has issue with the latest numpy, pinned to a different version.

Increasing hail RAM to 4GB, pandas upgrade.

---

cpg_infra/driver.py

After deploy and checking the members of the new AR-config group, I have noticed it contains only the first dataset, rest is missing.
This is bug is because the value key is the same across dataset.
Made a change to depends pulumi resource name on the group name, which is what we want.

Updating resource pulumi name for ar-config groups.

---

cpg_infra/driver.py

Group does not have display_name attribute, only name.
It is our Group class and not gcp.cloudidentity.Group, which has both.

Fix name of the group for pulumi resource.

---

cpg_infra/driver.py

This PR removes all the members of AR config bucket, all member groups are added to bucket viewer group.
This prevents the 250 limit GC impose on member groups per resource.
There is no limit how many groups another group can have.
Will keep original code commented out for the time being.

Commenting out individual members for ar-config bucket

---

cpg_infra/billing_aggregator/aggregate/utils.py
cpg_infra/driver.py

There has been change 2 months ago which removed catching asyncio.TimeoutError,
causing seqr aggregation to randomly fail.
I had rollback to generic Exception as it was prior to 'Migrate slack bot' PR.

Billing aggregation timeout exception

---

cpg_infra/billing_aggregator/aggregate/utils.py
cpg_infra/billing_aggregator/driver.py

This PR contains improvements regarding RAM usage, before we filter only on partition (by day +-1), which for heavy days produce huge amount of records causing the aggregation run out of RAM.
Extra filter has been added to filter further by usage_end_date, which significantly lower RAM usage.
From simple testing only around 1GB would be needed, but will keep it at 4GB for time being, we can check the usage in a few weeks and if we found 4GB is too much we can lower it. From cost perspective this is not going to make much difference.

Billing aggregation improvements

---

cpg_infra/billing_aggregator/aggregate/gcp.py
cpg_infra/billing_aggregator/aggregate/seqr.py
cpg_infra/billing_aggregator/aggregate/utils.py

Fixed few issues after deploying last PR.:
1. TIMESTAMP and DATETIME are not compatible when using BETWEEN operator in BQ, need to provide the right types for the query.
2. GCP aggregation was using date(), where what we really need is datetime. Had remove the casting datetime to date.
3. Seqr had one more issue the filter was too wide when collecting data after making optimisation with previous PR:
https://github.com/populationgenomics/cpg-infrastructure/pull/278
Have tested all 3 functions.

Fixed few types issues when calling BQ.

---

cpg_infra/billing_aggregator/aggregate/aggregate_daily_extended_view.txt

BQ table has been updated to fix the seq group, however the pulumi script contains the old version.

Updating BQ view, with seq group fixes.

---

cpg_infra/driver.py

Until upstream Hail releases proper fixes for SET-261 and especially SET-247, we need to override the QoB JAR file always.

Temporarily add workflow.default_jar_spec_revision to infrastructure.toml

---

cpg_infra/driver.py

It appears that [SET-247](https://cpg-populationanalysis.atlassian.net/browse/SET-247)'s cost increase has been due to building an unoptimised (or similar) QoB JAR when we build it on our homegrown VM environment. Instead use a JAR (with PR populationgenomics/hail#353 applied) that has been built via a Hail CI deploy batch.
[SET-247]: https://cpg-populationanalysis.atlassian.net/browse/SET-247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update override to use a 0.2.133 QoB JAR built via CI

---

cpg_infra/billing_aggregator/aggregate/utils.py

It seems GCP added new field into invoice, called 'invoice.publisher_type'.
Our aggregated table does not contain it and BQ had failed to load it. 
This only happened so far when running locally and it is a bit of mystery why the loading is not failing yet on production.
Adding ignore for new fields makes it more future resilient, in case Google add any new fields to their billing records.

Ignore new GCP fields during billing aggregation.

---

cpg_infra/driver.py

Use a QoB JAR built today via a Hail CI deploy batch, which includes a fix for the "20 million string length" issue cherry-picked from an as-yet unreleased upstream fix (hail-is/hail#14129) and added logging to help identify the intermittent 400 Bad Request errors encountered locally (populationgenomics/hail#358).
This is a followup to #287 and #288. With a `default_jar_spec_revision` that includes fixes for all currently known QoB JAR problems, this will mean that individual pipelines don't need to specify their own `jar_spec_revision`.

Update QoB JAR override to include 20million fix and improved 400 logging

---

cpg_infra/billing_aggregator/driver.py

This PR increases Seqr and Hail aggregation Cloud runs RAM to 8GB, from 4GB, we had reached memory limit in one of the runs overnight.

RAM increase for billing aggregation functions.

---

cpg_infra/abstraction/gcp.py

We often get transient errors when creating service accounts, where they get created but some mysterious error happens that makes Pulumi think they haven't been created. Then when you re-run the deploy you get an error saying that the account already exists. The create_ignore_already_exists config option for the service account Pulumi construct should mean that creating the service account won't fail if it already exists.

Don't fail deploy if service account already exists

---

requirements.txt

This param wasn't included until v7.6 of pulumi-gcp where the terraform bridge was updated to 5.12.0
https://github.com/pulumi/pulumi-gcp/pull/1542
https://github.com/pulumi/pulumi-gcp/releases/tag/v7.6.0
We could update to an even more up-to-date version but trying to avoid compatibility problems with other dependencies

Upgrade pulumi-gcp to version where create_ignore_already_exists exists

---

cpg_infra/driver.py

Update the QoB JAR override again, primarily to make it correspond to the deployed 0.2.134 hail release. This is a followup to #287, #288, and #292. We are nearly at a point where we won't need or want to override the QoB JAR by default anymore.
Use a QoB JAR built via a Hail CI deploy batch. This includes release 0.2.134 (which fixes the "20 million string length" issue) and retains our added logging to help identify the intermittent 400 Bad Request errors previously encountered locally (SET-261).
The selected commit, 2bb197d63afd58f9452af306e0eb14d6924d0019, is 0.2.134.cpg1 as tagged for CPG image building purposes (cf populationgenomics/images#200 and populationgenomics/images#201).

Update QoB JAR override to be 0.2.134-based and include 400logging

---

cpg_infra/billing_aggregator/driver.py

GCP cloud function CPU amount can be only 1,2,4... number 3 is not accepted.
This PR is fixing it.

Updating CPU count for seqr billing aggregator function.

---

storage_visualization/main.py
storage_visualization/treemap.py

This PR is addressing the storage visualisation issue:
1. Increase treemap job to 14GB, even hail is already reporting it has 14GB, so might not be needed.
2. Limit error message to just 250 chars, this will prevent the spamming slack channel with large error dumps. 250 is just a random number.
3. After testing the new RC of kaleido, generating image for all 3 levels is still freezing when tested locally.
As one of the possible solution was to use only 2 levels for the image and all 3 levels for the html page. So if people need more details they can follow the link from the Slack message. To avoid double parsing the data and creating 2 copies of rows, this PR is just filtering out dataframe rows by names. Field name contains full path to the stored object, so it just counts number of …

Change to storage visualisation function.

---

cpg_infra/billing_aggregator/aggregate/ica.py
cpg_infra/billing_aggregator/aggregate/seqr24.py
cpg_infra/billing_aggregator/driver.py

This PR add a new seqr24 cloud function which migrates GCP billing records from previous day.
Reason behind is to capture billing info for Cromwell jobs as those are updated by GCP much later than the execution of the regular seqr scheduled job. 
Config update to allow this function to run is in this PR:
https://github.com/populationgenomics/cpg-infrastructure-private/pull/542
This PR as well contains small fix for ICA. None gets converted to string, where we need null for the json object.

SET-463 Add billing aggregation function to run seqr 24h behind.

---

storage_visualization/disk_usage.py

Our storage plots have gone haywire - from a 5MB HTML file a year ago to 500+MB now, these can't be rendered. 
My suspicion is that the Hail Object detection (highly nested directories) only applies to HT/MT, and was not aware of VDSs. A VDS is a direcotry containing two MTs, but stored as `reference_data` and `variant_data`, so they wouldn't independently be recognised by the `.mt` extension detection. 
This might be the one secret ingredient to make these reports usable again, or there may be some other underlying cause for the bloat, but in either scenario this feels like a good change to make.

Trim depth of recursion for VDS in storage-vis

---

storage_visualization/Dockerfile

Kaleido 1.0.0 was released on June 20th and [breaks our storage visualisation](https://batch.hail.populationgenomics.org.au/batches/625886/jobs/72) due to
```
Warning: You have Plotly version 5.24.1, which is not compatible with this version of Kaleido (1.0.0).
This means that static image generation (e.g. `fig.write_image()`) will not work.
Please upgrade Plotly to version 6.1.1 or greater, or downgrade Kaleido to version 0.2.1.
…
ValueError: 
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
$ pip install -U kaleido
```
The older plotly 5.x is required by Hail, so for now we prefer to continue to use the kaleido 0.2.1 we've previously used rather than upgrade the world.

Avoid recent incompatible kaleido 1.0.0 release

---

cpg_infra/billing_aggregator/aggregate/utils.py

Job attributes are transmitted as strings, including 'sequencing_groups' which would naturally be a Python list of sequencing group IDs but is encoded as a JSON list for transmission.
Decode the JSON string values of specified JSON_LABELS into lists etc. When the labels are re-encoded as a dict in JSON string form, these attribute values won't be double-encoded.
Context: https://centrepopgen.slack.com/archives/C05TVRB8N86/p1755574328932129

Decode JSON string label values such as 'sequencing_groups'
