- stack/__main__.py
- tokens/main.py
- tokens/repository-map.json
From analysis-runner. Please merge before #1
> Update stack last time (for history) before new version will replace it

- cpg_infra/driver.py
> Fix web-access access group membership

- stack/Pulumi.ourdna-browser.yaml
- tokens/repository-map.json
> Adds ourdna-browser dataset

- .pre-commit-config.yaml
- cpg_infra/config.py
- cpg_infra/driver.py
- stack/Pulumi.common.yaml
- stack/cpg.toml
- tokens/repository-map.json
Also:
- rename 'reference' common set
- remove cpg-common artifact registry as common dependency
This script manages the artifact registry permissions (which was imported manually).
> Add common stack 

- cpg_infra/driver.py
Already deployed.
- Fixes where a large number of dependent configs (using an invalid char separator)
- Minor error during fix on last branch
> Minor fixes to cpg-infra storage config generation

- stack/Pulumi.lof-curation.yaml
- stack/new_stack.py
- tokens/repository-map.json
Context: https://centrepopgen.slack.com/archives/C02MZ2Q045P/p1669779146193639?thread_ts=1660612510.221169&cid=C02MZ2Q045P
> Add lof-curation dataset

- stack/production.yaml
(This has already been released).
> Enable prophecy release

- stack/production.yaml
Is this all that's required to do this? 
https://centrepopgen.slack.com/archives/C0292GYDU65/p1674020372567769?thread_ts=1671148033.593839&cid=C0292GYDU65
> Add thousand-genomes and hgdp dependency for prophecy

- stack/production.yaml
Addresses: https://github.com/populationgenomics/seqr-private/issues/50
> Create acute-care shared egress project

- stack/production.yaml
Context: https://centrepopgen.slack.com/archives/C030X7WGFCL/p1675743196294449
> Set up shared bucket for broad-rgp

- autoclass_migration/README.md
- autoclass_migration/fix_pulumi_state.py
- stack/dev.yaml
Context: https://centrepopgen.slack.com/archives/C03FZL2EF24/p1675743644364579?thread_ts=1675732375.316309&cid=C03FZL2EF24
> Fix bucket attributes in Pulumi state to reflect Autoclass migration

- autoclass_migration/migrate_bucket.sh
An attempt to increase CPU utilization for the VMs that perform the migration.
> Use more threads Autoclass copy / delete

- stack/production.yaml
Context: https://centrepopgen.slack.com/archives/C018KFBCR1C/p1675902361046539
> Remove obsolete projects without data

- cpg_infra/driver.py
Untested, but something like this should work.
> Ensure trailing newline for members cache

- cpg_infra/abstraction/azure.py
- cpg_infra/abstraction/base.py
- cpg_infra/abstraction/gcp.py
- cpg_infra/driver.py
Context: https://centrepopgen.slack.com/archives/C030X7WGFCL/p1676239341416309?thread_ts=1675743196.294449&cid=C030X7WGFCL
> Add data manager to credentials generator

- .github/workflows/preview.yaml
- cpg_infra/driver.py
- requirements.txt
Similar to cpg-infra-private, but checkout infra-private and modify install.
> Add preview workflow

- cpg_infra/abstraction/base.py
- cpg_infra/abstraction/gcp.py
- cpg_infra/driver.py
Context: https://centrepopgen.slack.com/archives/C030X7WGFCL/p1676419823373629
+ add get roles for data-manager
> Fix service account admin / credentials admin + add get roles

- cpg_infra/driver.py
\+ fix the service-account access permission that was wrong again (admin doesn't give you access).
> Give data-manager roles/iam.roleViewer on shared project

- cpg_infra/config.py
See companion PR https://github.com/populationgenomics/cpg-infrastructure-private/pull/21.
> Change the default archive age to 0 days

- cpg_infra/driver.py
> Fix billing coordinator group

- cpg_infra/config.py
**Note**: depends on https://github.com/populationgenomics/cpg-infrastructure-private/pull/34 being merged. Do not deploy beforehand.
> Default-enable Autoclass

- tokens/repository-map.json
Context: https://centrepopgen.slack.com/archives/C018KFBCR1C/p1676950959620269?thread_ts=1676930772.845849&cid=C018KFBCR1C
> Add cpg-methods repository for hgdp-1kg dataset

- cpg_infra/driver.py
Context: https://github.com/populationgenomics/cpg-infrastructure-private/pull/37
> Lowercase group members in group cache

- tokens/repository-map.json
Related to https://github.com/populationgenomics/seqr-private/pull/66.
> Allow running seqr-private code for data management tasks

- cpg_infra/abstraction/azure.py
- cpg_infra/abstraction/base.py
- cpg_infra/abstraction/gcp.py
- cpg_infra/config.py
- cpg_infra/driver.py
In hindsight, it didn't really make much sense for the two repos to be so coupled, the infra_private is responsible for deploying, so it should just fill in the relevant bits of the config there.
This, + the actual budgets are implemented in https://github.com/populationgenomics/cpg-infrastructure-private/pull/47
> Implement monthly budgets in pulumi

- cpg_infra/abstraction/gcp.py
- cpg_infra/billing_aggregator/aggregate/gcp.py
- cpg_infra/billing_aggregator/aggregate/hail.py
- cpg_infra/billing_aggregator/aggregate/seqr.py
- cpg_infra/billing_aggregator/aggregate/utils.py
- cpg_infra/billing_aggregator/driver.py
- cpg_infra/driver.py
Already deployed to try and get billing working
> Disable request handling for billing cloudfunction

- cpg_infra/billing_aggregator/aggregate/utils.py
Stacks on: https://github.com/populationgenomics/hail/pull/275
> Switch aggregate billing to use new latest completed batch endpoint

- .pylintrc
- cpg_infra/billing_aggregator/aggregate/hail.py
- cpg_infra/billing_aggregator/aggregate/seqr.py
- cpg_infra/billing_aggregator/aggregate/utils.py
As discussed in our catch-up :)
> Simplify ID on hail-derived billing entries to avoid resource changes in the future

- cpg_infra/billing_aggregator/driver.py
Memory issues, bigger to be safer
> Bump memory for GCP aggregator

- .github/workflows/lint.yaml
- .github/workflows/preview.yaml
- .github/workflows/storage_visualization.yaml
- requirements.txt
- storage_visualization/disk_usage.py
- storage_visualization/main.py
- storage_visualization/requirements.txt
- storage_visualization/slack.toml
- storage_visualization/submit.py
- storage_visualization/treemap.py
Example: https://test-web.populationgenomics.org.au/common/storage_visualization/23-03-21/treemap.html
> Add storage visualization automation

- .github/workflows/storage_visualization.yaml
- ~~Running once as a test~~ Test failed as expected
> Add storage_visualization.yaml reqs

- .github/workflows/preview.yaml
Due to https://github.com/populationgenomics/cpg-infrastructure-private/pull/97
> Temporarily disable Azure

- cpg_infra/abstraction/azure.py
- cpg_infra/abstraction/base.py
- cpg_infra/abstraction/gcp.py
- cpg_infra/driver.py
Currently noop because we don't have any active Azure datasets.
> Update azure blob format

- requirements.txt
- Relevant issue: https://github.com/pulumi/pulumi-azure-native/issues/1324#issuecomment-1496058107
> Update azure requirement to address OIDC issue

- .github/workflows/preview.yaml
- cpg_infra/abstraction/gcp.py
- cpg_infra/abstraction/google_group_settings.py
- cpg_infra/abstraction/group_settings.py
- requirements.txt
Currently enabled for _all_ groups, but we could easily make that more customizable.
> Allow external members in Google Groups

- cpg_infra/billing_aggregator/aggregate/utils.py
- cpg_infra/billing_aggregator/monthly_aggregate/main.py
Simple bug fix. Should solve our aggregator issue.
> FIX: bug fix for get_start_and_end_from_request

- cpg_infra/billing_aggregator/aggregate/utils.py
- cpg_infra/billing_aggregator/monthly_aggregate/main.py
Just a clean up for consistency in the code. Switch to `:=` operator
> get start and end from request - small cleanup

- requirements.txt
> Rebump cpg-utils requirement

- cpg_infra/driver.py
Currently no automatic permissions, I think we manually maintain the github accounts - but the upcoming metamist changes can add themselves to this registry. This repo contains some extra linting changes my IDE decided to fix today.
> Add python artifact registry

- cpg_infra/driver.py
Reverts populationgenomics/cpg-infrastructure#152 because it keeps running a 404 error.
> Revert "Add python artifact registry"

- cpg_infra/utils.py
Extended utils function to accept map of file names to callable. This allows e.g.
1. including of binary files such as *.tar.gz
2. ability to add private packages to requirements.txt
> Metamist utils update

- requirements.txt
Deploys new infrastructure deployed here: https://github.com/populationgenomics/metamist/pull/532
> Add new metamist ETL infrastructure

- cpg_infra/driver.py
Adds a second dev container repository, with test permissions
> Add container registry for development

- cpg_infra/billing_aggregator/aggregate/seqr.py
To better aggregate data for GATK-SV runs.
FYI @violetbrina
> Add dataset override for seqr GCP

- cpg_infra/abstraction/gcp.py
- cpg_infra/billing_aggregator/driver.py
Reverts populationgenomics/cpg-infrastructure#182
> Revert "Give billing.coordinator_machine_account billing.viewer role"

- cpg_infra/config/config.py
- cpg_infra/driver.py
Context: https://docs.google.com/document/d/1kUfezhIAsVPFEHEVngvPezfae7XORoYCjjqdW5meYNw/edit
Tested that this works!
> Add internal users to all internal batch projects

- cpg_infra/billing_aggregator/aggregate/hail.py
- cpg_infra/billing_aggregator/aggregate/seqr.py
- cpg_infra/billing_aggregator/aggregate/utils.py
To be unique from 2023-01-01.
I love copilot's suggestion for the comment: _Later Michael here, I've changed my mind._
> Refactor key generation logic in hail and seqr

- .pre-commit-config.yaml
- cpg_infra/abstraction/google_group_settings.py
- cpg_infra/abstraction/hailbatch.py
- cpg_infra/billing_aggregator/monthly_aggregate/main.py
- cpg_infra/billing_aggregator/update_budget/main.py
- groups_cleanup/main.py
- pyproject.toml
- reorder_state_file.py
- storage_visualization/disk_usage.py
- storage_visualization/main.py
- storage_visualization/submit.py
- storage_visualization/treemap.py
- test/test_parse_values.py
`isort` is mostly enabled in vscode now, already in our pyproject.toml, so time to make things official.
Basically a test of: https://github.com/populationgenomics/cpg-python-template-repo/pull/12
> Add isort + bump pre-commit versions

- cpg_infra/abstraction/gcp.py
I wanted to rename a dataset, but keep the project, and this just causes me all sorts of pain 😓
> Skip deleting GCP projects

- cpg_infra/billing_aggregator/aggregate/hail.py
- cpg_infra/billing_aggregator/aggregate/seqr.py
Don't ask me why I explicitly ignored it 🤷
> Add job name to hail batch billing

- cpg_infra/billing_aggregator/aggregate/utils.py
Some small suggestions based on reloading data the other day
> Improve handling of invoice month edges

- .pre-commit-config.yaml
- cpg_infra/abstraction/azure.py
- cpg_infra/abstraction/base.py
- cpg_infra/abstraction/gcp.py
- cpg_infra/abstraction/google_group_settings.py
- cpg_infra/abstraction/hailbatch.py
- cpg_infra/abstraction/metamist.py
- cpg_infra/billing_aggregator/aggregate/gcp.py
- cpg_infra/billing_aggregator/aggregate/hail.py
- cpg_infra/billing_aggregator/aggregate/seqr.py
- cpg_infra/billing_aggregator/aggregate/utils.py
- cpg_infra/billing_aggregator/driver.py
- cpg_infra/billing_aggregator/monthly_aggregate/main.py
- cpg_infra/billing_aggregator/update_budget/main.py
- cpg_infra/config/config.py
- cpg_infra/config/deserializabledataclass.py
- cpg_infra/driver.py
- cpg_infra/plugin/__init__.py
- cpg_infra/utils.py
- groups_cleanup/main.py
- pyproject.toml
- scripts/repair_state_202306.py
- setup.py
- storage_visualization/disk_usage.py
- storage_visualization/main.py
- storage_visualization/submit.py
- storage_visualization/treemap.py
- test/test_parse_values.py
😓 More changes than I expected, mostly all type annotations with basically no functional changes.
> Enable ruff linter and fix as many linting errors as possible

- requirements.txt
- https://github.com/populationgenomics/metamist/pull/682
> Metamist ETL configuration take II

- cpg_infra/abstraction/gcp.py
- cpg_infra/abstraction/google_group_membership.py
- scripts/remove_group_memberships.py
- Refactor GCP imports and remove unused code
> Dynamic group membership deploy fixes

- cpg_infra/billing_aggregator/aggregate/seqr.py
- cpg_infra/billing_aggregator/aggregate/utils.py
No prompt, except I don't like it in the logs
> Fix pluralisation and improve seqr error message

- cpg_infra/abstraction/azure.py
- cpg_infra/abstraction/gcp.py
- cpg_infra/abstraction/google_group_membership.py
- cpg_infra/abstraction/hailbatch.py
- cpg_infra/config/config.py
- cpg_infra/config/deserializabledataclass.py
- cpg_infra/driver.py
- test/test_parse_values.py
Removes the last manual step of creating a new stack
> Automatic hail user creation

- .github/workflows/storage_visualization.yaml
Changed in: https://github.com/populationgenomics/cpg-infrastructure-private/pull/290
> Use new production-yaml path

- .github/workflows/lint.yaml
Per instructions: https://github.com/codecov/codecov-action
> Add CODECOV_TOKEN to linting workflow

- requirements.txt
Pinning to a new metamist-infra version
> Updating metamist-infra dependency.

- requirements.txt
And cpg-infra has the same regarding the boto3/botocore pins.
> Relaxing botocore/boto3 pins.

- requirements.txt
Trying to upgrade metamist-private in the cloud etl function.
> Pinning metamist to new version, forcing metamist-infra update.

- cpg_infra/config/config.py
Prompted by: https://github.com/populationgenomics/team-docs/pull/161#discussion_r1678501701
> Remove unused projects from a user

- cpg_infra/billing_aggregator/driver.py
A few fixes from trying to deploy the gcp-cost-control update from #246.
> Cost control fixes

- cpg_infra/billing_aggregator/aggregate/utils.py
- cpg_infra/billing_aggregator/driver.py
- cpg_infra/billing_aggregator/gcp_cost_control/__init__.py
- cpg_infra/billing_aggregator/gcp_cost_control/main.py
- Pubsub messages in cloudrun have a slightly revised format: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/f7828705deaeb743828a531d5c25bc2cc6505a06/run/pubsub/main.py#L30-L45
- Need to include `__init__.py` in the directory so it gets carried across during the `pip install` (or included in package data)
- Bump memory for seqr
- Reduce time to look forward / backwards (@milo-hyben, worth revisiting this pre-fetch IDs approach, as it's causing so many more memory issues
> Misc fixes

- .pre-commit-config.yaml
- cpg_infra/config/config.py
- cpg_infra/config/deserializabledataclass.py
- cpg_infra/driver.py
- storage_visualization/disk_usage.py
- test_stack/group_membership/__main__.py
Add the `--check-untyped-defs` mypy flag in pre-commit, and fix the corresponding issues.
> Mypy check untyped defs

- .pre-commit-config.yaml
- cpg_infra/abstraction/azure.py
- cpg_infra/abstraction/gcp.py
- cpg_infra/abstraction/google_group_membership.py
- cpg_infra/abstraction/hailbatch.py
- cpg_infra/abstraction/metamist.py
- cpg_infra/billing_aggregator/aggregate/hail.py
- cpg_infra/billing_aggregator/aggregate/seqr.py
- cpg_infra/billing_aggregator/aggregate/utils.py
- cpg_infra/billing_aggregator/driver.py
- cpg_infra/billing_aggregator/gcp_cost_control/main.py
- cpg_infra/billing_aggregator/gcp_cost_report_slack_bot/main.py
- cpg_infra/config/__init__.py
- cpg_infra/config/config.py
- cpg_infra/config/deserializabledataclass.py
- cpg_infra/driver.py
- cpg_infra/plugin/__init__.py
- cpg_infra/utils.py
- pyproject.toml
- reorder_state_file.py
- scripts/remove_group_memberships.py
- scripts/repair_state_202306.py
- storage_visualization/main.py
- storage_visualization/treemap.py
And upgrade other formatters
Most changes are due to now enforcing double to single quotes (a style set by Hail and that we followed).
> Replace black with ruff

- cpg_infra/billing_aggregator/driver.py
I have made cloud run function timeout customisable, need larger for seqr aggregate.
> Increase timeout for seqr aggregation cloud run to 15 minutes.

- cpg_infra/billing_aggregator/driver.py
Increased RAM and timeout for both seqr and hail aggregation functions.
> Adjusting billing aggregation timeouts and memory.

- cpg_infra/driver.py
The previous implementation had this functionality in CPGDatasetCloudInfrastructure class, where it should really sits in CPGInfrastructure, otherwise it creates multiple copies of the analysis-runner-config-viewers-group per dataset.
This mistake has been only discovered when trying to deploy.
This PR is fixing this issue.
> Implementing analysis-runner-config-viewers-group

- cpg_infra/driver.py
This adds a new tmp registry, just not sure if this is the way to do it so please offer any feedback on how to approach :)
> Adding images-tmp container repo

- storage_visualization/disk_usage.py
- storage_visualization/main.py
This PR implements changes cpu from 0.5 to 1, give storage_visualization around 7GB or RAM so it can complete seqr bucket calculations.
> Increase CPU to 1, give storage_visualization more RAM.

- storage_visualization/main.py
This PR is increasing RAM from 7GB to 8GB for storage visualisation. The last step which generates the tree hit the 7GB mark.
> Increase RAM for storage visualisation to 8GB.
